alter table advertiser_applications
  add column if not exists website_url text,
  add column if not exists public_reference text,
  add column if not exists privacy_consent_at timestamptz,
  add column if not exists converted_destination_id uuid references cooperatives(id) on delete set null,
  add column if not exists converted_advertiser_id uuid references advertiser_profiles(id) on delete set null,
  add column if not exists converted_sponsorship_id uuid references sponsorships(id) on delete set null,
  add column if not exists converted_contract_id uuid references advertising_commercial_contracts(id) on delete set null,
  add column if not exists converted_at timestamptz;

create unique index if not exists advertiser_applications_public_reference_uq
  on advertiser_applications(public_reference)
  where public_reference is not null;

create index if not exists advertiser_applications_conversion_idx
  on advertiser_applications(status, converted_at desc, created_at desc);

alter table advertising_events
  add column if not exists client_event_id uuid;

create unique index if not exists advertising_events_client_event_uq
  on advertising_events(client_event_id)
  where client_event_id is not null;

comment on column advertiser_applications.privacy_consent_at is
  'Timestamp of explicit consent to submit business/contact data for advertising follow-up. It is not consent for unrelated marketing.';

comment on column advertiser_applications.public_reference is
  'Opaque follow-up reference returned to the applicant. It must not encode email, phone, user id or other personal data.';

comment on column advertising_events.client_event_id is
  'Random per-event retry/deduplication id generated by the client. It is not a user, device, session, holding or plot identifier.';
