import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { buildCatastroSelectorMap,DEFAULT_CATASTRO_CENTER,MIN_CATASTRO_ZOOM,exteriorRings,geometryCenter,isSimpleImportablePolygon,panCenter,pnoaTileUrl,viewportBbox,type CatastroGeometry } from './catastro-selector-map.ts';
async function read(relativePath:string):Promise<string>{return readFile(new URL(relativePath,import.meta.url),'utf8');}
test('map-first viewport stays inside Catastro V1 bbox limits',()=>{const b=viewportBbox(DEFAULT_CATASTRO_CENTER,MIN_CATASTRO_ZOOM);assert.ok(b.maxLon-b.minLon>0&&b.maxLon-b.minLon<=0.05);assert.ok(b.maxLat-b.minLat>0&&b.maxLat-b.minLat<=0.05);});
test('map-first pan changes center without private plot',()=>{const n=panCenter(DEFAULT_CATASTRO_CENTER,17,100,-50);assert.notEqual(n.longitude,DEFAULT_CATASTRO_CENTER.longitude);});
test('complex Catastro geometry stays visible but non-importable',()=>{const p:CatastroGeometry={type:'Polygon',coordinates:[[[-3.5,37.7],[-3.49,37.7],[-3.49,37.71],[-3.5,37.7]]]};const m:CatastroGeometry={type:'MultiPolygon',coordinates:[[[[-3.5,37.7],[-3.49,37.7],[-3.49,37.71],[-3.5,37.7]]],[[[-3.48,37.7],[-3.47,37.7],[-3.47,37.71],[-3.48,37.7]]]]};assert.equal(isSimpleImportablePolygon(p),true);assert.equal(isSimpleImportablePolygon(m),false);assert.equal(exteriorRings(m).length,2);assert.ok(geometryCenter(m));});
test('PNOA uses official IGN WMTS GoogleMapsCompatible contract',()=>{const u=new URL(pnoaTileUrl(18,128743,101234));assert.equal(u.origin,'https://www.ign.es');assert.equal(u.pathname,'/wmts/pnoa-ma');assert.equal(u.searchParams.get('LAYER'),'OI.OrthoimageCoverage');assert.equal(u.searchParams.get('TILEMATRIXSET'),'GoogleMapsCompatible');const map=buildCatastroSelectorMap(DEFAULT_CATASTRO_CENTER,18,'pnoa');assert.ok(map.tiles.every(t=>t.href.startsWith('https://www.ign.es/wmts/pnoa-ma?')));});
test('selector remains explicit and server-verified',async()=>{const panel=await read('./PlotMapPanel.tsx');const selector=await read('./CatastroMapFirstSelector.tsx');const routes=await read('../../api/src/catastro-map-routes.ts');assert.match(panel,/CatastroMapFirstSelector/);assert.match(selector,/Buscar mis parcelas en el mapa/);assert.match(selector,/selectedReferences/);assert.match(selector,/14, 18 o 20 caracteres/);assert.match(selector,/Mi ubicación/);assert.match(selector,/no acredita titularidad ni propiedad/);assert.match(routes,/fetchCatastroParcelByReference\(reference\)/);});
test('batch review keeps olives individual and supports explicit shared irrigation and variety',async()=>{const review=await read('./CatastroBatchReview.tsx');const routes=await read('../../api/src/catastro-batch-import-routes.ts');assert.match(review,/Olivos en esta parcela/);assert.match(review,/Aplicar riego a todas/);assert.match(review,/Aplicar variedad a todas/);assert.doesNotMatch(review,/Aplicar olivos a todas/);assert.match(review,/Variedad principal o mezcla/);assert.match(review,/Notas \(opcional\)/);assert.match(review,/oliveVariety:d\.oliveVariety\.trim\(\)\|\|null/);assert.match(review,/Olivos, riego, variedad y notas son datos privados declarados por ti/);assert.match(review,/const VARIETIES=\['Picual'/);assert.doesNotMatch(review,/oliveVariety:'Picual'/);assert.match(routes,/oliveVariety\?: string \| null/);assert.match(routes,/olive_variety/);assert.match(routes,/fetchCatastroParcelByReference\(reference\)/);assert.match(routes,/await client\.query\('begin'\)/);assert.match(routes,/await client\.query\('commit'\)/);});
test('PNOA, SIGPAC and private plot layers remain visual aids',async()=>{const selector=await read('./CatastroMapFirstSelector.tsx');const overlays=await read('./OfficialMapOverlays.tsx');const styles=await read('./official-map-layers.css');assert.match(selector,/Ortofoto PNOA/);assert.match(selector,/Hemos vuelto al mapa sin perder tu selección/);assert.match(overlays,/\/api\/v1\/maps\/sigpac\/recintos\?/);assert.doesNotMatch(overlays,/method:\s*['"]POST['"]/);assert.match(styles,/pointer-events:\s*none/);});
test('editable agronomy profile is mounted and never infers Picual',async()=>{const panel=await read('./PlotMapPanel.tsx');const profile=await read('./PlotOliveCountPanel.tsx');const api=await read('../../api/src/plot-agronomy-routes.ts');assert.match(panel,/PlotOliveCountPanel/);assert.match(profile,/Ficha agrícola por parcela/);assert.match(profile,/Picual/);assert.doesNotMatch(profile,/useState\('Picual'\)/);assert.match(profile,/Densidad pendiente/);assert.match(api,/olive_variety/);assert.match(api,/canWrite/);});
