import { useEffect, useMemo, useState } from 'react';
import './catastro-batch-review.css';

type IrrigationType='dryland'|'irrigated'|'mixed'|'unknown';
type ReviewParcel={nationalCadastralReference:string;label:string|null;areaM2:number|null};
type Draft={name:string;oliveTreeCount:string;irrigationType:IrrigationType|'';oliveVariety:string;notes:string};
type ValidationItem={cadastralReference:string;status:'ready'|'duplicate'|'unsupported'|'upstream-error'|'invalid';message?:string};
type BatchFailure={error?:{message?:string};created:false;items:ValidationItem[]};
type BatchSuccess={created:true;items:Array<{id:string;name:string;cadastralReference:string;boundaryAreaHa:number;oliveTreeCount:number|null;irrigationType:IrrigationType|null;oliveVariety:string|null}>};
const VARIETIES=['Picual','Hojiblanca','Arbequina','Manzanilla','Lechín','Mixta'];
function defaultName(p:ReviewParcel){return p.label?`Parcela ${p.label}`:`Parcela ${p.nationalCadastralReference}`;}
function formatArea(v:number|null){return v==null||!Number.isFinite(v)?'Superficie oficial pendiente':`${new Intl.NumberFormat('es-ES',{maximumFractionDigits:4}).format(v/10000)} ha Catastro`;}
function statusLabel(s:ValidationItem['status']){if(s==='duplicate')return'Ya añadida';if(s==='unsupported')return'Geometría no importable';if(s==='upstream-error')return'No verificada';if(s==='invalid')return'Dato no válido';return'Lista';}
export function CatastroBatchReview({farmId,parcels,onCreated,onBack}:{farmId:string;parcels:ReviewParcel[];onCreated:(count:number)=>Promise<void>;onBack:()=>void}){
 const [drafts,setDrafts]=useState<Record<string,Draft>>({});const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [validation,setValidation]=useState<Record<string,ValidationItem>>({});
 useEffect(()=>{setDrafts(current=>{const next:Record<string,Draft>={};for(const p of parcels)next[p.nationalCadastralReference]=current[p.nationalCadastralReference]??{name:defaultName(p),oliveTreeCount:'',irrigationType:'',oliveVariety:'',notes:''};return next;});setValidation({});setError(null);},[parcels]);
 const invalidLocal=useMemo(()=>parcels.some(p=>{const d=drafts[p.nationalCadastralReference];if(!d?.name.trim()||d.oliveVariety.trim().length>80||d.notes.length>5000)return true;if(!d.oliveTreeCount.trim())return false;const n=Number(d.oliveTreeCount);return!Number.isInteger(n)||n<0||n>100000000;}),[drafts,parcels]);
 function patchDraft(ref:string,patch:Partial<Draft>){setDrafts(c=>({...c,[ref]:{...c[ref]!,...patch}}));setValidation(c=>{if(!c[ref])return c;const n={...c};delete n[ref];return n;});}
 function applyIrrigationToAll(value:IrrigationType){setDrafts(c=>Object.fromEntries(Object.entries(c).map(([k,v])=>[k,{...v,irrigationType:value}])));}
 function applyVarietyToAll(value:string){setDrafts(c=>Object.fromEntries(Object.entries(c).map(([k,v])=>[k,{...v,oliveVariety:value}])));}
 async function createPlots(){if(!parcels.length||invalidLocal){setError('Revisa nombres, olivos, variedad y notas antes de continuar.');return;}setSaving(true);setError(null);setValidation({});try{const response=await fetch(`/api/v1/farms/${farmId}/plots/import-catastro`,{method:'POST',credentials:'include',headers:{accept:'application/json','content-type':'application/json'},body:JSON.stringify({parcels:parcels.map(p=>{const d=drafts[p.nationalCadastralReference]!;return{cadastralReference:p.nationalCadastralReference,name:d.name.trim(),oliveTreeCount:d.oliveTreeCount.trim()===''?null:Number(d.oliveTreeCount),irrigationType:d.irrigationType||null,oliveVariety:d.oliveVariety.trim()||null,notes:d.notes.trim()||null};})})});const body=await response.json() as BatchSuccess|BatchFailure;if(!response.ok||!body.created){const f=body as BatchFailure;setValidation(Object.fromEntries(f.items.map(i=>[i.cadastralReference,i])));setError(f.error?.message??'No se ha creado ninguna parcela. Revisa los avisos del lote.');return;}await onCreated(body.items.length);}catch{setError('No se ha podido completar el alta. No se ha confirmado ninguna creación; vuelve a intentarlo cuando tengas conexión.');}finally{setSaving(false);}}
 return <div className="catastro-batch-review" aria-labelledby="catastro-batch-review-title"><div className="catastro-batch-review-heading"><div><p className="eyebrow">Paso 2 · Datos agrícolas</p><h3 id="catastro-batch-review-title">Completa cada parcela</h3><p>Catastro se volverá a consultar en el servidor antes de crear nada.</p></div><button className="ghost-button" type="button" onClick={onBack} disabled={saving}>Volver al mapa</button></div>
 <div className="catastro-batch-quick-actions"><span>Aplicar riego a todas:</span><button className="text-button" type="button" onClick={()=>applyIrrigationToAll('dryland')}>Secano</button><button className="text-button" type="button" onClick={()=>applyIrrigationToAll('irrigated')}>Regadío</button><button className="text-button" type="button" onClick={()=>applyIrrigationToAll('mixed')}>Mixto</button></div>
 <div className="catastro-batch-quick-actions"><span>Aplicar variedad a todas:</span>{VARIETIES.map(v=><button key={v} className="text-button" type="button" onClick={()=>applyVarietyToAll(v)} disabled={saving}>{v}</button>)}</div>
 <div className="catastro-batch-grid">{parcels.map((p,index)=>{const ref=p.nationalCadastralReference;const d=drafts[ref]??{name:defaultName(p),oliveTreeCount:'',irrigationType:'',oliveVariety:'',notes:''};const val=validation[ref];return <article className="card card-body catastro-batch-card" key={ref}><div className="catastro-batch-card-title"><span className="catastro-map-first-number">{index+1}</span><div><strong>{p.label?`Parcela ${p.label}`:ref}</strong><small>{ref} · {formatArea(p.areaM2)}</small></div>{val?<span className="badge">{statusLabel(val.status)}</span>:null}</div><label className="field"><span>Nombre en Mágina Olivo</span><input value={d.name} maxLength={120} onChange={e=>patchDraft(ref,{name:e.target.value})} disabled={saving}/></label><div className="inline-fields"><label className="field"><span>Olivos en esta parcela</span><input type="number" min="0" max="100000000" step="1" inputMode="numeric" value={d.oliveTreeCount} onChange={e=>patchDraft(ref,{oliveTreeCount:e.target.value})} placeholder="Ej. 236" disabled={saving}/></label><label className="field"><span>Riego</span><select value={d.irrigationType} onChange={e=>patchDraft(ref,{irrigationType:e.target.value as IrrigationType|''})}><option value="">Sin definir</option><option value="dryland">Secano</option><option value="irrigated">Regadío</option><option value="mixed">Mixto</option><option value="unknown">No lo sé</option></select></label></div><label className="field"><span>Variedad principal o mezcla</span><input maxLength={80} value={d.oliveVariety} onChange={e=>patchDraft(ref,{oliveVariety:e.target.value})} placeholder="Ej. Picual"/></label><label className="field"><span>Notas (opcional)</span><textarea maxLength={5000} value={d.notes} onChange={e=>patchDraft(ref,{notes:e.target.value})} placeholder="Nombre local, acceso, observaciones…"/></label>{val?.message?<div className="alert" role="alert">{val.message}</div>:null}</article>;})}</div>
 <div className="catastro-batch-confirmation"><div><strong>{parcels.length} parcela{parcels.length===1?'':'s'} preparada{parcels.length===1?'':'s'}</strong><small>El lote es todo-o-nada: si una referencia falla, no se crea ninguna.</small></div><button className="primary-button" type="button" onClick={()=>void createPlots()} disabled={saving||invalidLocal||!parcels.length}>{saving?'Verificando Catastro…':parcels.length===1?'Crear esta parcela':`Crear ${parcels.length} parcelas`}</button></div><p className="catastro-map-first-trust">Olivos, riego, variedad y notas son datos privados declarados por ti. Catastro y SIGPAC no los rellenan automáticamente.</p>{error?<div className="alert" role="alert">{error}</div>:null}</div>;
}
