import { BarChart3, CloudRain, GripVertical, Info, Newspaper, Sprout, Trees, Users } from 'lucide-react';
import { useState } from 'react';
import { HOME_PREFERENCES_KEY, readHomePreferences, type HomeSectionKey } from './home-preferences';
import { PublicNavigation } from './PublicNavigation';
import { VisualHeader } from './VisualChrome';
const details: Record<HomeSectionKey, { title: string; copy: string; icon: typeof BarChart3 }> = {
  market: { title: 'Precio del AOVE', copy: 'Sigue la evolución del mercado con fuentes públicas.', icon: BarChart3 }, weather: { title: 'Alertas meteorológicas', copy: 'Anticipa cambios en tu zona.', icon: CloudRain }, news: { title: 'Noticias locales', copy: 'Toda la actualidad del sector en tu comarca.', icon: Newspaper }, cooperatives: { title: 'Cooperativas', copy: 'Consulta información de las entidades de la comarca.', icon: Users }, field: { title: 'Mi Campo', copy: 'Accede rápidamente a tus parcelas.', icon: Sprout }, olive: { title: 'Mi Olivo', copy: 'Seguimiento de recompensas y aceitunas.', icon: Trees },
};
export function HomePreferencesPage() {
  const [items, setItems] = useState(readHomePreferences); const [notice, setNotice] = useState<string | null>(null);
  const toggle = (key: HomeSectionKey) => { setItems((current) => current.map((item) => item.key === key ? { ...item, enabled: !item.enabled } : item)); setNotice(null); };
  const save = () => { localStorage.setItem(HOME_PREFERENCES_KEY, JSON.stringify(items)); window.dispatchEvent(new Event('magina:home-preferences')); setNotice('Preferencias de inicio guardadas en este dispositivo.'); };
  return <main className="account-shell home-preferences-shell"><VisualHeader /><PublicNavigation activePath="/cuenta" /><div className="account-page"><a className="profile-back-link" href="/cuenta">← Perfil</a><section><p className="eyebrow page-eyebrow">MI PERFIL</p><h1 className="section-title">Preferencias de Inicio</h1><p className="section-copy">Elige qué información quieres ver primero en tu pantalla de inicio.</p></section><section className="section home-preferences-note"><Info aria-hidden="true" /><span><strong>Tu inicio, a tu medida</strong><small>Activa o desactiva las secciones que más te interesan.<br />Puedes cambiar el orden arrastrando los elementos.</small></span></section>{notice ? <div className="alert success section" role="status">{notice}</div> : null}<section className="section home-preference-list">{items.map((item) => { const meta = details[item.key]; const Icon = meta.icon; return <article className="card home-preference-row" key={item.key}><span className="profile-link-icon"><Icon aria-hidden="true" /></span><span><strong>{meta.title}</strong><small>{meta.copy}</small></span><button className={`profile-switch${item.enabled ? ' is-on' : ''}`} type="button" role="switch" aria-label={meta.title} aria-checked={item.enabled} onClick={() => toggle(item.key)}><span /></button><GripVertical className="home-preference-grip" aria-hidden="true" /></article>; })}</section><div className="section edit-profile-actions"><button className="primary-button" type="button" onClick={save}>Guardar preferencias</button></div></div></main>;
}
